# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.data-source-properties.sslmode=require
spring.datasource.hikari.data-source-properties.ssl=true
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.web.resources.add-mappings=false
spring.jpa.show-sql=false

# Server
server.port=${PORT:8080}
